export const SETLOCALE = "app/set-locale";

export const API_GET_BACKLOG_ITEMS_REQUEST = "API_GET_BACKLOG_ITEMS_REQUEST";
export const API_GET_BACKLOG_ITEMS_SUCCESS = "API_GET_BACKLOG_ITEMS_SUCCESS";
export const API_GET_BACKLOG_ITEMS_FAILURE = "API_GET_BACKLOG_ITEMS_FAILURE";
