export const SET_LOCALE = "app/set-locale";
export const SET_EDIT_MODE = "app/set-edit-mode";

export const API_GET_BACKLOG_ITEMS_REQUEST = "API_GET_BACKLOG_ITEMS_REQUEST";
export const API_GET_BACKLOG_ITEMS_SUCCESS = "API_GET_BACKLOG_ITEMS_SUCCESS";
export const API_GET_BACKLOG_ITEMS_FAILURE = "API_GET_BACKLOG_ITEMS_FAILURE";

export const ROUTE_PLAN_VIEW = "ROUTE_PLAN_VIEW";
export const ROUTE_SPRINT_VIEW = "ROUTE_SPRINT_VIEW";
export const ROUTE_REVIEW_VIEW = "ROUTE_REVIEW_VIEW";
